name: scholar-research
version: 1
description: Global idea spec -> phased proposals -> tasks/apply/verify -> evidence-locked paper

artifacts:
  - id: idea
    generates: research/idea.md
    description: Single global Idea Spec (formulation + protocols + IDs)
    template: idea.md
    instruction: |
      Create or update the single global idea spec at research/idea.md.
      Requirements:
      - Must include divergence log with >=3 candidate directions (I*).
      - Must include stable IDs: H*, F*, C*.
      - Must include an assumptions/risk register linked to H/F/C.
      - Must include a locked evaluation protocol section (to be frozen).
      - Must include a proposal handoff capsule for `/proposal`.
      - Must maintain a Decision Log and Open Questions.
      - Never fabricate citations; mark UNVERIFIED if not verifiable.
    requires: []

  - id: idea_meta
    generates: research/idea.meta.yaml
    description: Idea state machine and counters
    template: idea.meta.yaml
    instruction: |
      Create or update idea.meta.yaml.
      - state: draft|frozen
      - version: vX.Y
      - counters: proposal_counter, amendment_counter
    requires: []

  - id: evidence
    generates: research/evidence-ledger.md
    description: Claim→Evidence→Pointer ledger
    template: evidence-ledger.md
    instruction: |
      Create or update the evidence ledger. All paper-facing claims must appear here.
      Status values: planned|partial|verified|falsified.
    requires: [idea]

  - id: proposal
    generates: research/proposals/Pxx-<slug>/proposal.md
    description: Phase proposal (scope + targeted IDs + success/kill criteria)
    template: proposal.md
    instruction: |
      Create a phase proposal folder and write proposal.md.
      It must explicitly list targeted H*/F*/C* IDs from research/idea.md.
      It must consume the proposal handoff capsule from research/idea.md.
    requires: [idea, idea_meta, evidence]

  - id: experiment_plan
    generates: research/proposals/Pxx-<slug>/experiment-plan.md
    description: Experiment plan aligned to the idea (NO results)
    template: experiment-plan.md
    instruction: |
      Write experiment-plan.md for this proposal.
      - Define experiments E* mapping to H* via F* and supporting C*.
      - Pre-register metric/tuning protocol/seeds/statistics.
      - No results allowed in this file.
    requires: [proposal]

  - id: tasks
    generates: research/proposals/Pxx-<slug>/tasks.md
    description: Trackable task checklist (apply phase uses this)
    template: tasks.md
    instruction: |
      Create tasks.md using strict checkbox format.
      Each task must contain:
      - command
      - expected outputs (paths)
      - acceptance criteria
      - links to E*/H*/F*/C*
    requires: [experiment_plan]

  - id: experiment_report
    generates: research/proposals/Pxx-<slug>/experiment-report.md
    description: Results report with artifact pointers
    template: experiment-report.md
    instruction: |
      Report results with pointers to logs/configs/figures/tables.
      Update evidence-ledger pointers and statuses accordingly.
    requires: [tasks]

  - id: verify
    generates: research/proposals/Pxx-<slug>/verify.md
    description: Audit falsification, reproducibility, and evidence closure
    template: verify.md
    instruction: |
      Verify:
      - Falsification criteria (F*)
      - Reproducibility completeness
      - Evidence ledger updated
      Decide next step:
      - fix plan / new proposal / idea amendment
    requires: [experiment_report, evidence]

  - id: idea_amendment
    generates: research/idea-amendments/Axx-<slug>.md
    description: Controlled change request to the frozen idea
    template: idea-amendment.md
    instruction: |
      If idea is frozen and changes are required, create an amendment request.
      Do not edit idea.md unless user explicitly accepts the amendment.
    requires: [verify, idea_meta]

  - id: claim_evidence_map
    generates: research/paper/claim-evidence-map.md
    description: Paper-facing claim map derived from evidence ledger
    template: claim-evidence-map.md
    instruction: |
      Produce claim-evidence-map.md from evidence-ledger.md.
      Only VERIFIED claims can appear in Abstract/Contributions.
    requires: [evidence, verify]

  - id: manuscript
    generates: research/paper/manuscript.md
    description: Manuscript draft locked to evidence pointers
    template: manuscript.md
    instruction: |
      Write manuscript using claim-evidence-map.md.
      No fabricated citations; all key citations must be verifiable.
    requires: [claim_evidence_map]

  - id: rebuttal
    generates: research/paper/rebuttal.md
    description: Rebuttal letter template
    template: rebuttal.md
    instruction: |
      Draft rebuttal as structured responses + action list.
    requires: [manuscript]

apply:
  requires: [tasks]
  tracks: research/proposals/**/tasks.md
  instruction: |
    Execute pending tasks step-by-step.
    Only check off tasks after outputs exist.
    Keep experiment-report and evidence-ledger updated as you go.
    Stop when blocked; request user input for missing decisions.
